name: cat_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  bloc_test: ^8.0.2
  equatable: ^2.0.3
  http: ^0.13.3
  formz: ^0.4.0
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.1.0
  very_good_analysis: ^2.1.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  cached_network_image: ^3.1.0
  auto_route: ^2.4.0
  dartz: ^0.10.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.8.0
  google_sign_in: ^5.0.0
  flutter_login_facebook: ^1.1.0
  get_it: ^7.2.0

dev_dependencies:
  mocktail: ^0.1.0
  flutter_native_splash: ^1.2.1
  auto_route_generator: ^2.4.0 
  build_runner: ^2.1.2

dependency_overrides:
  meta: ^1.7.0


flutter_native_splash: 
  color: "#ffffff"
  image: assets/images/cat.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:    
    - assets/images/cat.png
  