name: cat_app_core

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: 0.17.0
  flutter:
    sdk: flutter
  path_provider: 2.0.2

# dev_dependencies:
#   intl_translation: ^0.17.8

flutter:
  uses-material-design: true